### ISSUE TITLE
Update library

### ISSUE THREAD

**Issue by shytikov** [ilich/Cake.GitPackager#4]
Hi, 

Trying to use GitPackager with most recent version of Cake `0.27.2` shows following error message:

```
Could not find any assemblies compatible with .NETFramework,Version=v4.6.1 in NuGet package Cake.GitPackager. Falling back to using root folder of NuGet package.
The addin Cake.GitPackager will reference Cake.GitPackager.dll.
The addin Cake.GitPackager will reference LibGit2Sharp.dll.
Verifying assembly 'Cake.GitPackager, Version=0.1.2.42255, Culture=neutral, PublicKeyToken=null'.
Error: Cake.Core.CakeException: The assembly 'Cake.GitPackager, Version=0.1.2.42255, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.23.0).
This assembly must reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
   at Cake.Core.Reflection.AssemblyVerifier.Verify(Assembly assembly)
   at Cake.Core.Reflection.AssemblyLoader.Load(FilePath path, Boolean verify)
   at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
   at Cake.Commands.BuildCommand.Execute(CakeOptions options)
   at Cake.CakeApplication.Run(CakeOptions options)
   at Cake.Program.Main()
```

Is it possible to issue update for this library and upload it to NuGet?

Many thanks in advance!

**Comment by ilich** [comment]
Please try the latest version.
